### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by Splaktar** [antongolub/yarn-audit-fix#125]
```bash
$ npx yarn-audit-fix
yarn run v1.22.10
$ yarn-audit-fix
Runtime digest
Failure!
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function])
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at join (/Users/myuser/node_modules/find-up/index.js:11:14)
    at Function.module.exports.sync (/Users/myuser/node_modules/find-up/index.js:43:12)
    at Object.getClosestNpm (/Users/myuser/node_modules/yarn-audit-fix/target/es5/util.js:107:29)
    at Object.getNpm (/Users/myuser/node_modules/yarn-audit-fix/target/es5/util.js:121:24)
    at printRuntimeDigest (/Users/myuser/node_modules/yarn-audit-fix/target/es5/stages.js:39:26)
    at Object.exec (/Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:88:13)
    at /Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:104:25
    at step (/Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:33:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
(node:7953) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function])
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at join (/Users/myuser/node_modules/find-up/index.js:11:14)
    at Function.module.exports.sync (/Users/myuser/node_modules/find-up/index.js:43:12)
    at Object.getClosestNpm (/Users/myuser/node_modules/yarn-audit-fix/target/es5/util.js:107:29)
    at Object.getNpm (/Users/myuser/node_modules/yarn-audit-fix/target/es5/util.js:121:24)
    at printRuntimeDigest (/Users/myuser/node_modules/yarn-audit-fix/target/es5/stages.js:39:26)
    at Object.exec (/Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:88:13)
    at /Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:104:25
    at step (/Users/myuser/node_modules/yarn-audit-fix/target/es5/runner.js:33:23)
(node:7953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I see this with NodeJS v12.21.0 using NPM 7.14.0 and NPM 6.14.13. I see this with `yarn-audit-fix` versions 5.0.1 and 4.3.6.

I don't see this error with `yarn-audit-fix@3.3.3`, but that version doesn't update my `yarn.lock` with any of the fixes.

**Comment by antongolub** [comment]
Hey, @Splaktar,

It's so strange. Which  **find-up** version is loaded?

**Comment by Splaktar** [comment]
```
├─ find-cache-dir@3.3.1
│  └─ find-up@4.1.0
├─ find-up@1.1.2
├─ pkg-dir@5.0.0
│  └─ find-up@5.0.0
└─ protractor@7.0.0
   └─ find-up@4.1.0
```

**Comment by antongolub** [comment]
Still can not reproduce, sorry/ As I can see, function type is used as `path.resolve` argument. But I have no idea where it comes from.
Could you add `yarn-audit-fix` to your project, then go to `./node_modules/yarn-audit-fix/target/es5/util.js` and put some logging/debug inside this block to find out?
```
var getClosestNpm = function (cmd) {
    return String(find_up_1.sync(function (dir) {
        var ref = path_1.resolve(dir, 'node_modules', '.bin', cmd);
        return fs_extra_1.default.existsSync(ref) ? ref : undefined;
    }, {
        cwd: String(pkg_dir_1.sync(__dirname))
    }));
};
```
Btw, you may try another utility: [https://www.npmjs.com/package/yarn-audit-fix-ng](https://www.npmjs.com/package/yarn-audit-fix-ng). Hope this helps.

**Comment by Splaktar** [comment]
From
```js
var getClosestNpm = function (cmd) {
  console.log(`cmd = ${cmd}`);
  console.log(`pkg_dir_1 = ${pkg_dir_1.sync(__dirname)}`);
  const find_up_val = find_up_1.sync(function (dir) { <--- It doesn't like that this is a Function and not a string
    console.log(`dir = ${dir}`);
    var ref = path_1.resolve(dir, 'node_modules', '.bin', cmd);
    console.log(`ref = ${ref} and exists = ${fs_extra_1.default.existsSync(ref)}`);
    return fs_extra_1.default.existsSync(ref) ? ref : undefined;
  }, {
    cwd: String(pkg_dir_1.sync(__dirname))
  });
  console.log(`find_up_val = ${find_up_val}`)
```
Output
```
cmd = npm
pkg_dir_1 = /Users/myuser/myapp/node_modules/yarn-audit-fix
Failure!
```

**Comment by antongolub** [comment]
@Splaktar,

No idea, sorry. So we need to dive deeper and find out what's going on inside `find_up_1.sync`.
