### ISSUE TITLE
Error: `EINVALIDTAGNAME`

### ISSUE THREAD

**Issue by peisenmann** [antongolub/yarn-audit-fix#128]
I'm getting the following error, both for `npx yarn-audit-fix` and installing it to my project and running `yarn yarn-audit-fix`:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

When I check the debug logs, I see:
```
1978 timing idealTree Completed in 14515ms
1979 timing command:audit Completed in 23151ms
1980 verbose stack Error: Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
1980 verbose stack     at invalidTagName (~/project/node_modules/npm/node_modules/npm-package-arg/npa.js:94:15)
1980 verbose stack     at fromRegistry (~/project/node_modules/npm/node_modules/npm-package-arg/npa.js:300:13)
1980 verbose stack     at Function.resolve (~/project/node_modules/npm/node_modules/npm-package-arg/npa.js:84:12)
1980 verbose stack     at Arborist.[nodeFromEdge] (~/project/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:943:37)
1980 verbose stack     at async Arborist.[loadPeerSet] (~/project/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1164:23)
1980 verbose stack     at async Arborist.[buildDepStep] (~/project/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:880:11)
1980 verbose stack     at async Arborist.buildIdealTree (~/project/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
1980 verbose stack     at async Arborist.reify (~/project/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
1980 verbose stack     at async Audit.audit (~/project/node_modules/npm/lib/audit.js:66:5)
1981 verbose cwd ~/project/node_modules/.cache/yarn-audit-fix/77ed225c58f766d8c86e01106481319e
1982 verbose Darwin 19.5.0
1983 verbose argv "~/.nvm/versions/node/v12.4.0/bin/node" "~/project/node_modules/yarn-audit-fix/node_modules/.bin/npm" "audit" "fix" "--package-lock-only" "--prefix" "~/project/node_modules/.cache/yarn-audit-fix/77ed225c58f766d8c86e01106481319e"
1984 verbose node v12.4.0
1985 verbose npm  v7.14.0
1986 error code EINVALIDTAGNAME
1987 error Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
1988 verbose exit 1
```

To debug further, I modifed `~/project/node_modules/npm/node_modules/npm-package-arg/npa.js` and added this `console.log`
```
  } else {
    if (encodeURIComponent(spec) !== spec) {
      console.log('Invalid Tag Name', res)
      throw invalidTagName(spec)
    }
    res.type = 'tag'
  }
```
which produced this:
```
Invalid Tag Name Result {
  type: undefined,
  registry: true,
  where: undefined,
  raw: 'react@>=^16.0.0',
  name: 'react',
  escapedName: 'react',
  scope: undefined,
  rawSpec: '>=^16.0.0',
  saveSpec: null,
  fetchSpec: '>=^16.0.0',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined
}
Invalid Tag Name Result {
  type: undefined,
  registry: true,
  where: undefined,
  raw: 'react@>=^16.0.0',
  name: 'react',
  escapedName: 'react',
  scope: undefined,
  rawSpec: '>=^16.0.0',
  saveSpec: null,
  fetchSpec: '>=^16.0.0',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined
}
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

The funny thing is, I can't find that react version referenced anywhere in `yarn.lock`, so it must be getting created inadvertently in the conversion to `package-lock.json`, but I added 
```
    fs_extra_1.default.writeFileSync(path_1.join('~/project/', 'package-lock.json'), pgkLockJsonData);
```
into `stages.js` and was able to view the temporary package-lock file, and it didn't contain anything like `>=^` anywhere in it.

I'd be happy to PR a fix for this, but at this point, I had to give up for time. Any ideas what's going on would be great. Thanks!

**Comment by peisenmann** [comment]
Not sure what changed, but when I attempted `npx yarn-audit-fix` today, it completed without error. Prior to running it, I ran `yarn audit` and yielded
```
20951 vulnerabilities found - Packages audited: 4467
Severity: 9969 Low | 350 Moderate | 10628 High | 4 Critical
```
and after running `npx yarn-audit-fix`
```
20869 vulnerabilities found - Packages audited: 4465
Severity: 9963 Low | 294 Moderate | 10610 High | 2 Critical
```
So, I guess that's something. Historically, I feel like `npm audit fix` clears out a lot more than that, but I didn't investigate further at this time.

**Comment by antongolub** [comment]
yarn-audit-fix v6 uses an alternative patch strategy: it just fetches actual `yarn audit --json` advisories, and only applies those that satisfy to current yarn.lock semver ranges. `--flow=patch` does not rebuild dep tree unlike `--flow = convert`
