### ISSUE TITLE
find-up appears to be an undeclared runtime dependency

### ISSUE THREAD

**Issue by olivierlacan** [antongolub/yarn-audit-fix#179]
```
$ yarn run yarn-audit-fix
yarn run v1.22.0
$ /Users/olivierlacan/Development/ps/repo/node_modules/.bin/yarn-audit-fix
file:///Users/olivierlacan/Development/ps/repo/node_modules/yarn-audit-fix/target/es6/util.js:4
import { findUpSync, pathExistsSync } from 'find-up';
         ^^^^^^^^^^
SyntaxError: Named export 'findUpSync' not found. The requested module 'find-up' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'find-up';
const { findUpSync, pathExistsSync } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:142:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Not quite familiar with these errors but shouldn't find-up be a runtime dependency? https://github.com/antongolub/yarn-audit-fix/blob/2b7f5aba9c852a0fc6b60de2a6109b63f913dd80/src/main/ts/util.ts#L4

It's only listed in `devDependencies`: https://github.com/antongolub/yarn-audit-fix/blob/9a05ac923ce96ec0869430fc57c8c0627f33231b/package.json#L98

**Comment by antongolub** [comment]
Good catch, thanks!

**Comment by olivierlacan** [comment]
Thanks for the super quick resolution! 👍
