### ISSUE TITLE
Errors running on windows in git bash: EPERM operation not permitted, could not find parent dir

### ISSUE THREAD

**Issue by klues** [antongolub/yarn-audit-fix#18]
I get the following error on running `npx yarn-audit-fix` on windows in git bash:
```
npx yarn-audit-fix
Preparing temp assets...
Error: EPERM: operation not permitted, symlink '..\..' -> 'C:\data\src\<my project>\node_modules\.cache\yarn-audit-fix\node_modules'
```

running the same in a console with administrator privileges results in this error:
```
npx yarn-audit-fix
Preparing temp assets...
Generating package-lock.json from yarn.lock...
Error: Could not find parent dir!
    at parentPackagePath (C:\data\src\<my project>\node_modules\synp\util\traverse.js:9:11)
    at C:\data\src\<my project>\node_modules\synp\lib\lockfileV1\tree.js:67:30
``` 

thanks for any hints to get it running.

**Comment by antongolub** [comment]
Hi @klues

There're some issues with **synp** and **yarn-audit-fix** we're trying to solve rigth now. Could you try out the latest 2.0.0-rc.5?
```
npx yarn-audit-fix@2.0.0-rc.5
```

**Comment by MattSwartz** [comment]
Same thing here. I did try the 2.0.0-rc.5 with the same results. See below

```
$ npx yarn-audit-fix@2.0.0-rc.5 --symlink=junction
npx: installed 375 in 11.943s
Preparing temp assets...
Generating package-lock.json from yarn.lock...
Error: Could not find parent dir!
    at parentPackagePath (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\util\traverse.js:9:11)
    at C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV1\tree.js:65:30
    at Array.reduce (<anonymous>)
    at buildNpmTree (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV1\tree.js:51:8)
    at convertYarnToNpmV1 (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV1\index.js:13:26)
    at convertYarnToNpm (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\index.js:15:9)
    at Object.yarnToNpm (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\index.js:15:12)
    at yarnLockToPkgLock (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\target\es5\index.js:90:42)
    at C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\target\es5\index.js:179:21
    at step (C:\Users\matt\AppData\Roaming\npm-cache\_npx\33692\node_modules\yarn-audit-fix\target\es5\index.js:33:23)
```
Let me know what information I can supply to help.

**Comment by antongolub** [comment]
Oh... It seems to be all about path separators. Could you try **2.0.0-rc.6**?

**Comment by antongolub** [comment]
@MattSwartz @klues 

I've added windows os to build matrix. Everything seems to be ok.
https://travis-ci.com/github/antongolub/yarn-audit-fix/jobs/375950459

**Comment by klues** [comment]
thank you very much for the support!

I've tried rc7, this is the result:
```
npx yarn-audit-fix@2.0.0-rc.7 --symlink=junction
npx: Installierte 375 in 12.618s
Preparing temp assets...
Generating package-lock.json from yarn.lock...
Applying npm audit fix...
invoke node node_modules/npm/bin/npm-cli.js audit fix --prefix=C:\data\src\<my-project>\node_modules\.cache\yarn-audit-fix
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\data\src\<my-project>\node_modules\.cache\yarn-audit-fix\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11764,
  stdout: null,
  stderr: null
}
```

**Comment by antongolub** [comment]
@klues

I'll assume this is because npm v7 is trying to eliminate the difference in the `node_modules` directory structure. Let's try this workaround: 
1. Restore original `node_modules` state. `yarn --force` or `rm-rf node_modules && yarn`.
2. Apply `npx yarn-audit-fix@2.0.0-rc.7 --symlink=junction --package-lock-only`. The last param should instruct **npm** not to modify `node_modules` contents.

**Comment by klues** [comment]
I did
```
rm -rf node_modules
rm -rf yarn.lock
yarn
npx yarn-audit-fix@2.0.0-rc.7 --symlink=junction --package-lock-only
```

but unfortunately it results in the same error.
Maybe this line is the problem:
`invoke node node_modules/npm/bin/npm-cli.js audit fix --prefix=C:\data\src\<my-project>\node_modules\.cache\yarn-audit-fix`
where the current `node_modules\.cache` directory is passed as `--prefix`?!

**Comment by antongolub** [comment]
@klues

Most likely you are right. I'll experiment with this a little later.

**Comment by antongolub** [comment]
If there is no objections, I'm going to close this for now as the main issue seems to be solved.
