### ISSUE TITLE
Synp fails on attempt to convert undefined or null to object

### ISSUE THREAD

**Issue by antongolub** [antongolub/yarn-audit-fix#20]
rc.11 does get past the first part then bombs out here:

```removed 699 packages in 20s

found 0 vulnerabilities
npm timing command:audit Completed in 19147ms
npm verb exit [ 0, true ]
npm timing npm Completed in 19956ms
npm info ok
Updating yarn.lock from package-lock.json...
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at flattenPackageLock (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\util\format.js:7:17)
    at buildYarnTree (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV1\tree.js:22:34)
    at convertNpmV1ToYarn (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV1\index.js:26:22)
    at convertNpmV2ToYarn (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\lockfileV2\index.js:84:12)
    at convertNpmToYarn (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\lib\index.js:31:9)
    at Object.npmToYarn (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\node_modules\@antongolub\synp\index.js:17:12)
    at yarnImport (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\target\es5\index.js:114:39)
    at C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\target\es5\index.js:179:21
    at step (C:\Users\matt\AppData\Roaming\npm-cache\_npx\44120\node_modules\yarn-audit-fix\target\es5\index.js:33:23)
```

_Originally posted by @MattSwartz in https://github.com/antongolub/yarn-audit-fix/issues/18#issuecomment-678277731_

**Comment by antongolub** [comment]
@MattSwartz

I've just tried to reproduce the issue, but couldn't. Here are my steps:

1. copy `package.json` + `yarn.lock`
2. invoke **yarn**
```
yaf-cannot-convert-undefined % yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 61.08s.
```
3. apply `npx yarn-audit-fix`
```
yaf-cannot-convert-undefined % npx yarn-audit-fix
npx: installed 376 in 8.582s
Preparing temp assets...
Generating package-lock.json from yarn.lock...
Applying npm audit fix...
invoke npm audit fix --package-lock-only --prefix=/Users/a.golub/temp/yaf-cannot-convert-undefined/node_modules/.cache/yarn-audit-fix
added 27 packages, removed 6 packages and updated 1195 packages in 3.495s
fixed 497 of 498 vulnerabilities in 1185 scanned packages
  1 vulnerability required manual review and could not be updated
Updating yarn.lock from package-lock.json...
invoke yarn --update-checksums
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
warning @symfony/webpack-encore > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 4.83s.
Done
```

Can you confirm that the problem still persists?

**Comment by antongolub** [comment]
@MattSwartz

Maybe you have any other examples?

**Comment by antongolub** [comment]
Hey, @MattSwartz,

[synp](https://github.com/imsnif/synp) got a [big patch](https://github.com/imsnif/synp/compare/v1.8.2...v1.9.3) just recently. I think this should solve all the problems, so I'm closing this issue for now. If not feel free to open another one bug ticket.
