### ISSUE TITLE
SyntaxError: Unknown token: { line: 4, col: 2, type: 'INVALID', value: undefined } 4:2 in lockfile

### ISSUE THREAD

**Issue by stee-ren** [antongolub/yarn-audit-fix#204]
I've deleted the yarn.lock and tried this using bash and cmd with no success. Does this tool only support specific versions of yarn (and the associated lock file)?

```
D:\WORK\frontend>yarn-audit-fix
Runtime digest

  isMonorepo false
  npmPath D\\WORK\\frontend\\node_modules\\yarn-audit-fix\\node_modules\\.bin\\npm.cmd
  npmVersion 8.1.2
  nodeVersion v14.18.1
  yafVersion 7.1.5
  temp D\\WORK\\frontend\\node_modules\\.cache\\yarn-audit-fix\\04610f6eea2bfb3e8bb3333ee22ac42b
  cwd D\\WORK\\frontend
  flags
    flow patch
    npm-path local


Preparing temp assets...
Patching yarn.lock with audit data...
Failure!
SyntaxError: Unknown token: { line: 4, col: 2, type: 'INVALID', value: undefined } 4:2 in lockfile
    at Parser.unexpected (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5064:11)
    at Parser.parse (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5193:14)
    at parse (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5262:17)
    at Object.module.exports.exports.default (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:4835:96)
    at Object._read (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/lockfile.js:7:21)
    at Module.read (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/lockfile.js:89:44)
    at patchLockfile (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/stages.js:144:25)
    at exec (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/runner.js:30:13)
    at Function.runSync [as sync] (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/runner.js:41:9)
    at file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/cli.js:33:5
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

SyntaxError: Unknown token: { line: 4, col: 2, type: 'INVALID', value: undefined } 4:2 in lockfile
    at Parser.unexpected (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5064:11)
    at Parser.parse (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5193:14)
    at parse (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:5262:17)
    at Object.module.exports.exports.default (D:\WORK\frontend\node_modules\@yarnpkg\lockfile\index.js:4835:96)
    at Object._read (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/lockfile.js:7:21)
    at Module.read (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/lockfile.js:89:44)
    at patchLockfile (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/stages.js:144:25)
    at exec (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/runner.js:30:13)
    at Function.runSync [as sync] (file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/runner.js:41:9)
    at file:///D:/WORK/frontend/node_modules/yarn-audit-fix/target/es6/cli.js:33:5

D:\WORK\frontend>
```

**Comment by antongolub** [comment]
Hey, @stee-ren,

yarn-audit-fix interacts with lockfile through [@yarnpkg/lockfile](https://www.npmjs.com/package/@yarnpkg/lockfile) API . It's compatible with lockfile v1 format as we know from our experience with the tool. I'm afraid we haven't tested v2  compatibility at all.

**Comment by antongolub** [comment]
@stee-ren, @pladaria,

could you check the latest beta?
```shell
npm_config_yes=true npx yarn-audit-fix@9.0.0-beta.1
```

**Comment by stee-ren** [comment]
Just in case, I updated to the latest version of Yarn, made little difference - got the results below with Yarn 3.0.2 and latest

`
$ npm_config_yes=true npx yarn-audit-fix@9.0.0-beta.1                           
npx: installed 88 in 5.432s
Runtime digest
yarn-audit-fix version 9.0.0-beta.1 is out of date. Install the latest 9.0.1 for better results 
                                                                                                
  isMonorepo false                                                                              
  bins                                                                                          
    yarn yarn.cmd                                                                               
    npm npm.cmd                                                                                 
                                                                                                
  versions                                                                                      
    node v16.13.0                                                                               
    npm 6.14.15                                                                                 
    yarn 3.1.1                                                                                  
    yaf 9.0.0-beta.1                                                                            
    yafLatest 9.0.1                                                                             
                                                                                                
  temp D\\WORK\\frontend\\node_modules\\.cache\\yarn-audit-fix\\c4aa3c1aafd58460b79a511696c50150
  cwd D\\WORK\\frontend                                                                         
  flags                                                                                         
    flow patch                                                                                  
    npm-path system                                                                             


Verifying package structure...
Preparing temp assets...
Patching yarn.lock with audit data...
invoke yarn.cmd npm audit --all --json --recursive
Failure!
SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseAuditReport (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/v2.js:71:62)
    at audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/v2.js:69:12)
    at Object._audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/index.js:60:7)
    at Module.audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/index.js:71:45)
    at patchLockfile (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/stages.js:147:23)
    at exec (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/runner.js:45:13)
    at Function.runSync [as sync] (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/runner.js:56:9)
    at file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/cli.js:33:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
undefined:1
Internal Error: doppelmayr-d-services@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
^

SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseAuditReport (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/v2.js:71:62)
    at audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/v2.js:69:12)
    at Object._audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/index.js:60:7)
    at Module.audit (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/lockfile/index.js:71:45)
    at patchLockfile (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/stages.js:147:23)
    at exec (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/runner.js:45:13)
    at Function.runSync [as sync] (file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/runner.js:56:9)
    at file:///C:/Users/str/AppData/Roaming/npm-cache/_npx/27576/node_modules/yarn-audit-fix/target/es6/cli.js:33:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)

`

**Comment by antongolub** [comment]
@stee-ren, could you attach your audit report?

`yarn.cmd npm audit --all --json --recursive > report.json`

**Comment by stee-ren** [comment]
Here you go:
[report.zip](https://github.com/antongolub/yarn-audit-fix/files/7703961/report.zip)

**Comment by antongolub** [comment]
Seems like `Internal Error: doppelmayr-d-services@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile` was passed to the parser. I think it may be related to missed `.yarn` assets symlink. https://github.com/antongolub/yarn-audit-fix/compare/v9.0.1...v9.0.3

Try out v9.0.3, hope this helps.

**Comment by stee-ren** [comment]
That worked perfectly Anton, thank you for your super quick turn around on this.
One favor to ask - would you mind editing your comment to remove the company reference - embarrassing for me for not being more careful with the attachment

**Comment by antongolub** [comment]
Sure, sorry.
